
# constants are extracted from win32con, which is part of pywin32

"""
def _win32con_attributes():
    import win32con
    ATTRIBUTES = ['REG_BINARY', 'REG_DWORD', 'REG_DWORD_BIG_ENDIAN', 'REG_DWORD_LITTLE_ENDIAN', 'REG_EXPAND_SZ',
                   'REG_FULL_RESOURCE_DESCRIPTOR', 'REG_LINK', 'REG_MULTI_SZ', 'REG_NONE',
                   'REG_NOTIFY_CHANGE_ATTRIBUTES', 'REG_NOTIFY_CHANGE_SECURITY', 'REG_QWORD',
                   'REG_QWORD_LITTLE_ENDIAN', 'REG_RESOURCE_LIST', 'REG_RESOURCE_REQUIREMENTS_LIST', 'REG_SZ',
                   'HKEY_CLASSES_ROOT', 'HKEY_CURRENT_CONFIG', 'HKEY_CURRENT_USER',
                   'HKEY_LOCAL_MACHINE', 'HKEY_PERFORMANCE_DATA', 'HKEY_USERS',
                   'KEY_ALL_ACCESS', 'KEY_CREATE_LINK', 'KEY_ENUMERATE_SUB_KEYS', 'KEY_EXECUTE', 'KEY_NOTIFY',
                   'KEY_QUERY_VALUE', 'KEY_READ', 'KEY_SET_VALUE', 'KEY_WOW64_32KEY', 'KEY_WOW64_64KEY',
                   'KEY_WOW64_RES', 'KEY_WRITE']
    for name in ATTRIBUTES:
        yield (name, getattr(win32con, name))

def _print_win32_attribures():
    for name, value in _win32con_attributes():
        print '%s = %s' % (name, value)
"""

REG_BINARY = 3
REG_DWORD = 4
REG_DWORD_BIG_ENDIAN = 5
REG_DWORD_LITTLE_ENDIAN = 4
REG_EXPAND_SZ = 2
REG_FULL_RESOURCE_DESCRIPTOR = 9
REG_LINK = 6
REG_MULTI_SZ = 7
REG_NONE = 0
REG_NOTIFY_CHANGE_ATTRIBUTES = 2
REG_NOTIFY_CHANGE_SECURITY = 8
REG_QWORD = 11
REG_QWORD_LITTLE_ENDIAN = 11
REG_RESOURCE_LIST = 8
REG_RESOURCE_REQUIREMENTS_LIST = 10
REG_SZ = 1
HKEY_CLASSES_ROOT = -2147483648
HKEY_CURRENT_CONFIG = -2147483643
HKEY_CURRENT_USER = -2147483647
HKEY_LOCAL_MACHINE = -2147483646
HKEY_PERFORMANCE_DATA = -2147483644
HKEY_USERS = -2147483645
KEY_ALL_ACCESS = 983103
KEY_CREATE_LINK = 32
KEY_ENUMERATE_SUB_KEYS = 8
KEY_EXECUTE = 131097
KEY_NOTIFY = 16
KEY_QUERY_VALUE = 1
KEY_READ = 131097
KEY_SET_VALUE = 2
KEY_WOW64_32KEY = 512
KEY_WOW64_64KEY = 256
KEY_WOW64_RES = 768
KEY_WRITE = 131078

ERROR_SUCCESS = 0
ERROR_BAD_NETPATH = 53
RPC_S_INVALID_NET_ADDR = 1707
ERROR_ACCESS_DENIED = 5
ERROR_INVALID_HANDLE = 6
ERROR_INVALID_PARAMETER = 87
ERROR_FILE_NOT_FOUND = 2

MAX_KEYNAME_LENGTH = 256
ERROR_NO_MORE_ITEMS = 259
MAX_VALUENAME_LENGTH = 32767
